version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: node-app-123
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://sachinruriya:OmfJA4kuXnzrf5xL@crudapp.j55ln.mongodb.net/crudAPP?retryWrites=true&w=majority&appName=crudapp
    depends_on:
      - mongo
    volumes:
      - .:/app           # Syncs local files with the container
    command: ["npm", "run", "dev"]

  mongo:
    image: mongo:latest
    container_name: mongodb-123
    ports:
      - "27017:27017"    # Use MongoDB’s default port
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
